apiVersion: apps/v1
kind: Deployment
metadata:
  name: ward-admissions
  namespace: f21ao-ops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ward-admissions
  template:
    metadata:
      labels:
        app: ward-admissions
    spec:
      serviceAccountName: jenkins
      containers:
      - name: ward-admissions
        image: notvolk/zlf21ao-containers:ward-1.0.3
        ports:
        - containerPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-registration
  namespace: f21ao-ops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: patient-registration
  template:
    metadata:
      labels:
        app: patient-registration
    spec:
      serviceAccountName: jenkins
      containers:
      - name: patient-registration
        image: notvolk/zlf21ao-containers:reg-1.0.3
        ports:
        - containerPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-treatment
  namespace: f21ao-ops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab-treatment
  template:
    metadata:
      labels:
        app: lab-treatment
    spec:
      serviceAccountName: jenkins
      containers:
      - name: lab-treatment
        image: notvolk/zlf21ao-containers:lab-1.0.3
        ports:
        - containerPort: 3003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: f21ao-ops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: jenkins
      containers:
      - name: gateway
        image: notvolk/zlf21ao-containers:gateway-1.0.3
        ports:
        - containerPort: 3000