version: '3.9'

services:
  ward-admissions:
    build:
      context: ./services/ward-admissions-service
    container_name: ward-admissions
    image: notvolk/zlf21ao-containers:ward-1.0.3
    ports:
      - '3001:3001'
    volumes:
      - ./services/ward-admissions-service:/app
      - /app/node_modules

  patient-registration:
    build:
      context: ./services/patient-registration-service
    container_name: patient-registration
    image: notvolk/zlf21ao-containers:reg-1.0.3
    ports:
      - '3002:3002'
    volumes:
      - ./services/patient-registration-service:/app
      - /app/node_modules

  lab-treatment:
    build:
      context: ./services/lab-treatment-service
    container_name: lab-treatment
    image: notvolk/zlf21ao-containers:lab-1.0.3
    ports:
      - '3003:3003'
    volumes:
      - ./services/lab-treatment-service:/app
      - /app/node_modules

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    image: notvolk/zlf21ao-containers:gateway-1.0.3
    ports:
      - '3000:3000'
    volumes:
      - ./gateway:/app
      - /app/node_modules